local status_ok, nvim_tree = pcall(require, 'nvim-tree')
if not status_ok then
  return
end

nvim_tree.setup({
  sort_by = 'case_sensitive',
  open_on_setup = true,
  open_on_setup_file = false,
  open_on_tab = true,
  reload_on_bufenter = true,
  view = {
    adaptive_size = true,
    mappings = {
      custom_only = false,
      list = {
        { key = { "<CR>", "o", "l", "<2-LeftMouse>" }, action = "edit" },
        { key = "<C-e>",                               action = "edit_in_place" },
        { key = "O",                                   action = "edit_no_picker" },
        { key = { "<C-]>", "<2-RightMouse>" },         action = "cd" },
        { key = "<C-v>",                               action = "vsplit" },
        { key = "<C-x>",                               action = "split" },
        { key = "<C-t>",                               action = "tabnew" },
        { key = "<",                                   action = "prev_sibling" },
        { key = ">",                                   action = "next_sibling" },
        { key = "P",                                   action = "parent_node" },
        { key = { "<BS>", "h" },                       action = "close_node" },
        { key = "<Tab>",                               action = "preview" },
        { key = "K",                                   action = "first_sibling" },
        { key = "J",                                   action = "last_sibling" },
        { key = "I",                                   action = "toggle_git_ignored" },
        { key = "H",                                   action = "toggle_dotfiles" },
        { key = "U",                                   action = "toggle_custom" },
        { key = "R",                                   action = "refresh" },
        { key = "a",                                   action = "create" },
        { key = "d",                                   action = "remove" },
        { key = "D",                                   action = "trash" },
        { key = "r",                                   action = "rename" },
        { key = "<C-r>",                               action = "full_rename" },
        { key = "x",                                   action = "cut" },
        { key = "c",                                   action = "copy" },
        { key = "p",                                   action = "paste" },
        { key = "y",                                   action = "copy_name" },
        { key = "Y",                                   action = "copy_path" },
        { key = "gy",                                  action = "copy_absolute_path" },
        { key = "[c",                                  action = "prev_git_item" },
        { key = "]c",                                  action = "next_git_item" },
        { key = "-",                                   action = "dir_up" },
        { key = "s",                                   action = "system_open" },
        { key = "f",                                   action = "live_filter" },
        { key = "F",                                   action = "clear_live_filter" },
        { key = "q",                                   action = "close" },
        { key = "W",                                   action = "collapse_all" },
        { key = "E",                                   action = "expand_all" },
        { key = "S",                                   action = "search_node" },
        { key = ".",                                   action = "run_file_command" },
        { key = "<C-k>",                               action = "toggle_file_info" },
        { key = "g?",                                  action = "toggle_help" },
      },
    },
  },
  renderer = {
    add_trailing = true,
    group_empty = true,
    highlight_git = true,
    icons = {
      webdev_colors = false,
      show = {
        file = false,
        folder = false,
        folder_arrow = false,
        git = false,
      },
    },
    special_files = {
      "Makefile",
      "README.md", "readme.md",
      "README.adoc", "readme.adoc",
    },
  },
  filters = {
    dotfiles = false,
  },
})
